version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./php
    volumes: 
      - ./code:/code
    links:
      - mariadb
  mariadb:
    image: mariadb:10.5.8-focal
    volumes:
      - ./db:/var/lib/mysql
    environment:
        TZ: "America/Toronto"
        MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_ARBITRARY: 1
